In [2]:
import numpy as np


In [3]:
ide = np.identity(45)

In [4]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [5]:
ide.size

2025

In [6]:
ide.shape

(45, 45)

In [7]:
arr = np.arange(99)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [9]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [10]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [11]:
arr.shape

(99,)

In [12]:
x = [[1, 2, 3],[4, 5, 6], [7, 1, 0]]

In [13]:
ar = np.array(x)

In [14]:
ar.sum(axis=0)

array([12,  8,  9])

In [15]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [16]:
ar.T



array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [18]:
 ar.flat

In [21]:
for item in ar.flat:
      print(item)

1
2
3
4
5
6
7
1
0


In [22]:
sum = 0
for i in ar.flat:
    sum+=i
print(sum)

29


In [23]:
ar.ndim

2

In [24]:
ar.size

9

In [25]:
ar.nbytes

72

In [26]:
ar.nbytes

72

In [27]:
one = np.array([1, 3, 4, 634, 7])

In [28]:
one.argmax()

np.int64(3)

In [29]:
one.argmin()

np.int64(0)

In [31]:
one.argsort()

array([0, 1, 2, 3, 4])

In [32]:
ar.argmax(axis=0)

array([2, 1, 1])

In [33]:
ar.argmax(axis=1)

array([2, 2, 0])

In [34]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [35]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [36]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [37]:
ar.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [41]:
ar2 = np.array([[1, 2, 1],[3, 0, 2],[4, 8, 3]])

In [42]:
ar+ar2

array([[ 2,  4,  4],
       [ 7,  5,  8],
       [11,  9,  3]])

In [43]:
ar-ar2

array([[ 0,  0,  2],
       [ 1,  5,  4],
       [ 3, -7, -3]])

In [44]:
ar*ar2

array([[ 1,  4,  3],
       [12,  0, 12],
       [28,  8,  0]])

In [45]:
ar/ar2

C:\Users\Harshita Sinha\AppData\Local\Temp\ipykernel_6476\2166607628.py:1: RuntimeWarning: divide by zero encountered in divide
  ar/ar2


array([[1.        , 1.        , 3.        ],
       [1.33333333,        inf, 3.        ],
       [1.75      , 0.125     , 0.        ]])

In [46]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [47]:
ar.sum()

np.int64(29)

In [49]:
ar.max()

np.int64(7)

In [50]:
ar.min()

np.int64(0)

In [52]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [53]:
type(np.where(ar>5))

tuple

In [54]:
np.count_nonzero(ar)

np.int64(8)

In [56]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [57]:
import sys

In [58]:
py_ar = [1, 2, 3, 4]

In [59]:
np_ar = np.array(py_ar)

In [60]:
sys.getsizeof(1)*len(py_ar)

112

In [61]:
np_ar.itemsize*np_ar.size

32